server:
  port: 80

spring:
  application:
    name: spring-jwt-6
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:chuonghoang}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    locations:
      classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /





